/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
// VENTANA DE VENTAS
public class VentasJFrame extends javax.swing.JFrame {

    // 3 LISTA GENERICAS, UN CLIENTE QUE SERA EL CLIENTE QUE REALIZA LA COMPRA Y EL TOTAL DE LAS COMPRAS
    public ListaGen clientes = new ListaGen();
    public ListaGen productos = new ListaGen();
    public Cliente clienteActual;
    public ListaGen carrito = new ListaGen();
    public double total = 0.00;
    
    /**
     * Creates new form VentasJFrame
     */
    public VentasJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); // VENTANA CENTRADA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consulta = new javax.swing.JButton();
        comprar_btn = new javax.swing.JButton();
        carrito_btn = new javax.swing.JButton();
        fin_btn = new javax.swing.JButton();
        cliente_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Ventas");

        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        comprar_btn.setText("Comprar");
        comprar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprar_btnActionPerformed(evt);
            }
        });

        carrito_btn.setText("Carrito");
        carrito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrito_btnActionPerformed(evt);
            }
        });

        fin_btn.setText("Finalizar Compra");
        fin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin_btnActionPerformed(evt);
            }
        });

        cliente_label.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(comprar_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(carrito_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(fin_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cliente_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(consulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cliente_label)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprar_btn)
                    .addComponent(carrito_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(fin_btn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // RECORRE LA LISTA DE PRODUCTOS Y TE NOTIFICA SI EXISTE EL PRODUCTO O NO POR MEDIO DE SU CLAVE
    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
        int claveBus = Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la clave del producto a buscar:","Busqueda",JOptionPane.INFORMATION_MESSAGE));
        boolean encontrado = false;
        for( var producto :  this.productos.list)
        {
            Producto pro = (Producto) producto;
            if(pro.getClave() == claveBus)
            {
                encontrado = true;
                JOptionPane.showMessageDialog(this, "Producto Encontrado: \n" + pro.toString(),"Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        if(encontrado == false)
        JOptionPane.showMessageDialog(this, "Producto No Existente", "Resultado", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_consultaActionPerformed
    
    // RECORRE LA LISTA DE PRODUCTOS Y TE NOTIFICA SI EXISTE O NO POR MEDIO DE SU CLAVE PARA REALIZAR LA COMPRA (TAMBIEN VERIFICA SI HAY SUFICIENTES EN EXISTENCIA PARA COMPRAR)
    private void comprar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprar_btnActionPerformed
        // TODO add your handling code here:
        int claveBus = Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la clave del producto a comprar:","Comprar",JOptionPane.INFORMATION_MESSAGE));
        boolean encontrado = false;
        int i = 0;
        for( var producto :  this.productos.list)
        {
            Producto pro = (Producto) producto;
            if(pro.getClave() == claveBus)
            {
                encontrado = true;
                if(pro.getExis()<= 0)
                {
                    JOptionPane.showMessageDialog(this, "Producto Agotado", "Agotado", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    Producto nuevo = (Producto) this.productos.list.get(i);
                    nuevo.reducirExis(1);
                    this.productos.list.set(i,nuevo);
                    this.carrito.agregar(pro);
                    this.total += pro.getPrecio();
                    JOptionPane.showMessageDialog(this, "Producto " + pro.getClave() +" agregado al Carrito de Compras","Resultado", JOptionPane.INFORMATION_MESSAGE);    
                }
            }
            i++;
        }
        if(encontrado == false)
            JOptionPane.showMessageDialog(this, "Producto No Existente", "Resultado", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_comprar_btnActionPerformed

    // TE MUESTRA LA LISTA DE CARRITO QUE ES LA LISTA DE LO QUE COMPRA EL CLIENTE
    private void carrito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrito_btnActionPerformed
        // TODO add your handling code here:
         String resume = ""; 
        int i = 1;
        for( var producto :  this.carrito.list)
        {
            Producto pro = (Producto) producto;
            resume += "Producto " + i + "\nClave: " + pro.getClave() + "\nPrecio: "+ pro.getPrecio() +"\n\n";
            i++;
        }
        resume += "Subtotal: " + this.total + "\nIva: " + (this.total*.16) + "\nTotal: " + (this.total + (this.total*.16));
        JOptionPane.showMessageDialog(this, resume,"Carrito de Compras de " + this.clienteActual.getNombre(), JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_carrito_btnActionPerformed

   // TE MUESTRA EL CARRITO DE COMPRAS Y CIERRA LA VENTANA DE VENTAS
    private void fin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin_btnActionPerformed
        // TODO add your handling code here:
        String resume = ""; 
        int i = 1;
        for( var producto :  this.carrito.list)
        {
            Producto pro = (Producto) producto;
            resume += "Producto " + i + "\nClave: " + pro.getClave() + "\nPrecio: "+ pro.getPrecio() +"\n\n";
            i++;
        }
        resume += "Subtotal: " + this.total + "\nIva: " + (this.total*.16) + "\nTotal: " + (this.total + (this.total*.16));
        this.dispose();
        JOptionPane.showMessageDialog(this, resume,"Recibo de " + this.clienteActual.getNombre(), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_fin_btnActionPerformed
    
    // mETODO "PRINCIPAL" QUE RECIBE AMBAS LISTAS PARA OCUPARLAS Y LUEGO DEVOLVERLAS ACTUALIZADAS
    public void frame(ListaGen clientes, ListaGen productos)
    {
        this.clientes = clientes;
        this.productos = productos;
        
        // BUSCA SI EXISTE EL CLIENTE SI EXISTE O NO
        // SI EXISTE TE MUESTRA LA VENTA DE VENTAS NOTIFICANDO QUE CLIENTE ENTRO
        // EN CASO CONTRARIO TE NOTIFICA QUE NO EXISTE CLIENTE
        int claveBus = Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la clave del cliente:","Compras",JOptionPane.INFORMATION_MESSAGE));
        boolean encontrado = false;
        for( var cliente :  this.clientes.list)
        {
            Cliente cli = (Cliente) cliente;
            if(cli.getClave() == claveBus)
            {
                this.clienteActual = cli;
                encontrado = true;
                this.cliente_label.setText("Cliente Actual: " + this.clienteActual.getNombre());
                this.setVisible(true);
            }
        }
        if(encontrado == false)
            JOptionPane.showMessageDialog(this, "Cliente Inexistente", "Resultado", JOptionPane.WARNING_MESSAGE);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carrito_btn;
    private javax.swing.JLabel cliente_label;
    private javax.swing.JButton comprar_btn;
    private javax.swing.JButton consulta;
    private javax.swing.JButton fin_btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
