/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CapaGrafica;

import CapaDatos.RegistroClientes;
import CapaDatos.RegistroProductos;
import CapaLogica.Producto;
import CapaLogica.Usuario;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class AdminForm extends javax.swing.JFrame {
    
    public RegistroClientes registroAdmin;
    public RegistroProductos registroAdminPro;

    /** Creates new form AdminForm */
    public AdminForm() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.registroAdmin = new RegistroClientes();
        this.registroAdminPro = new RegistroProductos();
        this.setLocationRelativeTo(null); // VENTENA EN CENTRO DE LA PANTALLA
        // POR DEFECTO LEE LOSA RCHIVO .SER PARA ACTUALIZAR LAS JLIST
        this.listaUsuarios.setModel(this.registroAdmin.actualizarJList());
        this.listaProductos.setModel(this.registroAdminPro.actualizarJList());
        this.listaProductosAlquiler.setModel(this.registroAdminPro.actualizarJListAlquiler());
        /*
        DefaultListModel model = new DefaultListModel();
        model.addElement("123456789    Roberto    65    admin@videoclub.com    Administrador");
        this.listaUsuarios.setModel(model);
        this.listaUsuarios.removeAll();
        model.clear();
         model.addElement("123456789    Roberto    66    admin@videoclub.com    Administrador");
        */
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed = new javax.swing.JTabbedPane();
        clientePanel = new javax.swing.JPanel();
        registroPanel = new javax.swing.JPanel();
        registroLabel = new javax.swing.JLabel();
        nombreRes = new javax.swing.JLabel();
        nomFRes = new javax.swing.JTextField();
        nombreRes1 = new javax.swing.JLabel();
        nomFRes1 = new javax.swing.JTextField();
        nombreRes2 = new javax.swing.JLabel();
        nomFRes2 = new javax.swing.JTextField();
        nombreRes3 = new javax.swing.JLabel();
        nomFRes3 = new javax.swing.JTextField();
        nombreRes4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTipo = new javax.swing.JList<>();
        registrarBtn = new javax.swing.JButton();
        nombreRes5 = new javax.swing.JLabel();
        nomFRes4 = new javax.swing.JTextField();
        borrarPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTipoB = new javax.swing.JList<>();
        borrarLabel = new javax.swing.JLabel();
        bajaF = new javax.swing.JTextField();
        bajaBtn = new javax.swing.JButton();
        borrarLabel1 = new javax.swing.JLabel();
        listaPanel = new javax.swing.JPanel();
        listaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        listaLabel1 = new javax.swing.JLabel();
        listaLabel2 = new javax.swing.JLabel();
        listaLabel3 = new javax.swing.JLabel();
        listaLabel4 = new javax.swing.JLabel();
        listaLabel5 = new javax.swing.JLabel();
        listaLabel6 = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();
        mantenimientoPanel = new javax.swing.JPanel();
        registroPanelP = new javax.swing.JPanel();
        registroLabel1 = new javax.swing.JLabel();
        nombreRes6 = new javax.swing.JLabel();
        nomFPro = new javax.swing.JTextField();
        nombreRes7 = new javax.swing.JLabel();
        nombreRes10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaTipoP = new javax.swing.JList<>();
        registrarBtn1 = new javax.swing.JButton();
        nombreRes11 = new javax.swing.JLabel();
        comboExistencia = new javax.swing.JComboBox<>();
        comboAnio = new javax.swing.JComboBox<>();
        listaPanelPro = new javax.swing.JPanel();
        listaLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        listaLabel8 = new javax.swing.JLabel();
        listaLabel9 = new javax.swing.JLabel();
        listaLabel10 = new javax.swing.JLabel();
        eleminarBtnPro = new javax.swing.JButton();
        modificarBtnPro = new javax.swing.JButton();
        listaLabel11 = new javax.swing.JLabel();
        listaPanelProAlquiler = new javax.swing.JPanel();
        listaLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaProductosAlquiler = new javax.swing.JList<>();
        listaLabel13 = new javax.swing.JLabel();
        listaLabel14 = new javax.swing.JLabel();
        listaLabel15 = new javax.swing.JLabel();
        listaLabel16 = new javax.swing.JLabel();
        borrarPanel1 = new javax.swing.JPanel();
        borrarLabel2 = new javax.swing.JLabel();
        consultaF = new javax.swing.JTextField();
        consultaBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaTipoPConsulta = new javax.swing.JList<>();
        borrarLabel3 = new javax.swing.JLabel();
        fondoLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        clientePanel.setLayout(null);

        registroPanel.setBackground(new java.awt.Color(0, 0, 0,90));

        registroLabel.setForeground(new java.awt.Color(255, 255, 255));
        registroLabel.setText("Registro de Clientes");

        nombreRes.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes.setText("Nombre: ");

        nombreRes1.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes1.setText("Edad:");

        nombreRes2.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes2.setText("Telefono:");

        nombreRes3.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes3.setText("Correo:");

        nombreRes4.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes4.setText("Tipo de Cliente:");

        listaTipo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Administrador", "Normal", "VIP" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaTipo);

        registrarBtn.setBackground(new java.awt.Color(51, 204, 0));
        registrarBtn.setText("Registrar");
        registrarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        nombreRes5.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes5.setText("Contraseña:");

        javax.swing.GroupLayout registroPanelLayout = new javax.swing.GroupLayout(registroPanel);
        registroPanel.setLayout(registroPanelLayout);
        registroPanelLayout.setHorizontalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addComponent(registroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreRes)
                            .addComponent(nombreRes1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomFRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomFRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nombreRes4)
                                .addGap(0, 21, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nombreRes2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomFRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroPanelLayout.createSequentialGroup()
                                .addComponent(nombreRes3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomFRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreRes5)
                            .addComponent(nomFRes4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        registroPanelLayout.setVerticalGroup(
            registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroLabel)
                .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomFRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRes))
                        .addGap(8, 8, 8)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomFRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRes1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomFRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRes2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomFRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRes3))
                        .addGap(35, 35, 35)
                        .addComponent(registrarBtn)
                        .addGap(26, 26, 26))
                    .addGroup(registroPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreRes4)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreRes5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomFRes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        clientePanel.add(registroPanel);
        registroPanel.setBounds(20, 20, 310, 240);

        borrarPanel.setBackground(new java.awt.Color(0, 0, 0,90));

        listaTipoB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Administrador", "Normal", "VIP" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaTipoB);

        borrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        borrarLabel.setText("Baja de Clientes");

        bajaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaFActionPerformed(evt);
            }
        });

        bajaBtn.setBackground(new java.awt.Color(255, 0, 0));
        bajaBtn.setText("Baja");
        bajaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bajaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaBtnActionPerformed(evt);
            }
        });

        borrarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        borrarLabel1.setText("ID del Cliente");

        javax.swing.GroupLayout borrarPanelLayout = new javax.swing.GroupLayout(borrarPanel);
        borrarPanel.setLayout(borrarPanelLayout);
        borrarPanelLayout.setHorizontalGroup(
            borrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(borrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajaF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        borrarPanelLayout.setVerticalGroup(
            borrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarPanelLayout.createSequentialGroup()
                .addGroup(borrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(borrarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrarLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bajaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(bajaBtn)
                .addContainerGap())
        );

        clientePanel.add(borrarPanel);
        borrarPanel.setBounds(360, 90, 300, 120);

        listaPanel.setBackground(new java.awt.Color(0, 0, 0,90));

        listaLabel.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel.setText("Lista de Clientes");

        jScrollPane1.setViewportView(listaUsuarios);

        listaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel1.setText("ID");

        listaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel2.setText("Nombre");

        listaLabel3.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel3.setText("Edad");

        listaLabel4.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel4.setText("Correo");

        listaLabel5.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel5.setText("Tipo de Usuario");

        listaLabel6.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel6.setText("Contraseña");

        javax.swing.GroupLayout listaPanelLayout = new javax.swing.GroupLayout(listaPanel);
        listaPanel.setLayout(listaPanelLayout);
        listaPanelLayout.setHorizontalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                    .addGroup(listaPanelLayout.createSequentialGroup()
                        .addGroup(listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(listaPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(listaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(listaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(listaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(listaLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(listaLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(listaLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        listaPanelLayout.setVerticalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaLabel)
                .addGap(2, 2, 2)
                .addGroup(listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaLabel1)
                    .addComponent(listaLabel2)
                    .addComponent(listaLabel3)
                    .addComponent(listaLabel4)
                    .addComponent(listaLabel5)
                    .addComponent(listaLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        clientePanel.add(listaPanel);
        listaPanel.setBounds(20, 290, 640, 150);

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaGrafica/img/admin.jpg"))); // NOI18N
        clientePanel.add(fondoLabel);
        fondoLabel.setBounds(0, 0, 670, 460);

        tabbed.addTab("Clientes", clientePanel);

        mantenimientoPanel.setLayout(null);

        registroPanelP.setBackground(new java.awt.Color(0, 0, 0,90));

        registroLabel1.setForeground(new java.awt.Color(255, 255, 255));
        registroLabel1.setText("Registro de Productos");

        nombreRes6.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes6.setText("Nombre: ");

        nombreRes7.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes7.setText("Año:");

        nombreRes10.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes10.setText("Tipo de Producto:");

        listaTipoP.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pelicula", "Videojuego", "Cartelera" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaTipoP);

        registrarBtn1.setBackground(new java.awt.Color(51, 204, 0));
        registrarBtn1.setText("Registrar");
        registrarBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registrarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtn1ActionPerformed(evt);
            }
        });

        nombreRes11.setForeground(new java.awt.Color(255, 255, 255));
        nombreRes11.setText("Existencia:");

        comboExistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "num", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        comboExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboExistenciaActionPerformed(evt);
            }
        });

        comboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        javax.swing.GroupLayout registroPanelPLayout = new javax.swing.GroupLayout(registroPanelP);
        registroPanelP.setLayout(registroPanelPLayout);
        registroPanelPLayout.setHorizontalGroup(
            registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelPLayout.createSequentialGroup()
                .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registroPanelPLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(comboExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroPanelPLayout.createSequentialGroup()
                                .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(registroPanelPLayout.createSequentialGroup()
                                        .addComponent(nombreRes6)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroPanelPLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(nombreRes7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomFPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreRes11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(2, 2, 2)))
                        .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroPanelPLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroPanelPLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nombreRes10))))
                    .addGroup(registroPanelPLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(registrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        registroPanelPLayout.setVerticalGroup(
            registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroPanelPLayout.createSequentialGroup()
                .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroPanelPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nombreRes10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registroPanelPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registroLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomFPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRes6))
                        .addGap(2, 2, 2)
                        .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreRes7)
                            .addComponent(nombreRes11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registroPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addComponent(registrarBtn1)
                .addContainerGap())
        );

        mantenimientoPanel.add(registroPanelP);
        registroPanelP.setBounds(20, 20, 310, 160);

        listaPanelPro.setBackground(new java.awt.Color(0, 0, 0,90));

        listaLabel7.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel7.setText("Lista de Productos en Stock");

        jScrollPane5.setViewportView(listaProductos);

        listaLabel8.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel8.setText("Codigo");

        listaLabel9.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel9.setText("Nombre");

        listaLabel10.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel10.setText("Existencia");

        eleminarBtnPro.setBackground(new java.awt.Color(255, 0, 0));
        eleminarBtnPro.setText("Eliminar");
        eleminarBtnPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eleminarBtnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleminarBtnProActionPerformed(evt);
            }
        });

        modificarBtnPro.setBackground(new java.awt.Color(255, 255, 0));
        modificarBtnPro.setText("Modificar");
        modificarBtnPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modificarBtnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnProActionPerformed(evt);
            }
        });

        listaLabel11.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel11.setText("Tipo");

        javax.swing.GroupLayout listaPanelProLayout = new javax.swing.GroupLayout(listaPanelPro);
        listaPanelPro.setLayout(listaPanelProLayout);
        listaPanelProLayout.setHorizontalGroup(
            listaPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelProLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listaPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(listaPanelProLayout.createSequentialGroup()
                        .addComponent(listaLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listaLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(listaLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listaLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(listaLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(listaPanelProLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(eleminarBtnPro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificarBtnPro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPanelProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        listaPanelProLayout.setVerticalGroup(
            listaPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelProLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(listaLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listaPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaLabel8)
                    .addComponent(listaLabel9)
                    .addComponent(listaLabel10)
                    .addComponent(listaLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listaPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eleminarBtnPro)
                    .addComponent(modificarBtnPro))
                .addContainerGap())
        );

        mantenimientoPanel.add(listaPanelPro);
        listaPanelPro.setBounds(20, 240, 360, 200);

        listaPanelProAlquiler.setBackground(new java.awt.Color(0, 0, 0,90));

        listaLabel12.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel12.setText("Lista de Productos en Alquiler");

        jScrollPane6.setViewportView(listaProductosAlquiler);

        listaLabel13.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel13.setText("Codigo");

        listaLabel14.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel14.setText("Nombre");

        listaLabel15.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel15.setText("Cantidad");

        listaLabel16.setForeground(new java.awt.Color(255, 255, 255));
        listaLabel16.setText("Tipo");

        javax.swing.GroupLayout listaPanelProAlquilerLayout = new javax.swing.GroupLayout(listaPanelProAlquiler);
        listaPanelProAlquiler.setLayout(listaPanelProAlquilerLayout);
        listaPanelProAlquilerLayout.setHorizontalGroup(
            listaPanelProAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelProAlquilerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listaPanelProAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(listaPanelProAlquilerLayout.createSequentialGroup()
                        .addComponent(listaLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(listaLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listaLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(listaLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPanelProAlquilerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        listaPanelProAlquilerLayout.setVerticalGroup(
            listaPanelProAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelProAlquilerLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(listaLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listaPanelProAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaLabel13)
                    .addComponent(listaLabel14)
                    .addComponent(listaLabel15)
                    .addComponent(listaLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        mantenimientoPanel.add(listaPanelProAlquiler);
        listaPanelProAlquiler.setBounds(360, 20, 300, 160);

        borrarPanel1.setBackground(new java.awt.Color(0, 0, 0,90));

        borrarLabel2.setForeground(new java.awt.Color(255, 255, 255));
        borrarLabel2.setText("Consulta de Productos");

        consultaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFActionPerformed(evt);
            }
        });

        consultaBtn.setBackground(new java.awt.Color(204, 0, 204));
        consultaBtn.setText("Consultar");
        consultaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        consultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBtnActionPerformed(evt);
            }
        });

        listaTipoPConsulta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pelicula", "Videojuego", "Cartelera" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listaTipoPConsulta);

        borrarLabel3.setForeground(new java.awt.Color(255, 255, 255));
        borrarLabel3.setText("Codigo del Producto");

        javax.swing.GroupLayout borrarPanel1Layout = new javax.swing.GroupLayout(borrarPanel1);
        borrarPanel1.setLayout(borrarPanel1Layout);
        borrarPanel1Layout.setHorizontalGroup(
            borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrarPanel1Layout.createSequentialGroup()
                        .addComponent(borrarLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarPanel1Layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarPanel1Layout.createSequentialGroup()
                                .addGroup(borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consultaF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(borrarPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(borrarPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(consultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarPanel1Layout.createSequentialGroup()
                                .addComponent(borrarLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
        );
        borrarPanel1Layout.setVerticalGroup(
            borrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrarLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrarLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultaBtn)
                .addContainerGap())
        );

        mantenimientoPanel.add(borrarPanel1);
        borrarPanel1.setBounds(430, 240, 190, 200);

        fondoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaGrafica/img/admin.jpg"))); // NOI18N
        mantenimientoPanel.add(fondoLabel1);
        fondoLabel1.setBounds(0, 0, 670, 460);

        tabbed.addTab("Mantenimiento", mantenimientoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// BOTON REGISTRAR CLIENTE
    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        // TODO add your handling code here:
        // VERIFICA QUE TODO ESTE LLENADO Y SELECCIONADO
        if (this.nomFRes.getText().isEmpty() || this.nomFRes1.getText().isEmpty() || this.nomFRes2.getText().isEmpty() || this.nomFRes3.getText().isEmpty() || this.nomFRes4.getText().isEmpty()  )
            JOptionPane.showMessageDialog(null, "Falta de llenar algun espacio","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else if(this.listaTipo.getSelectedValue() == null)
            JOptionPane.showMessageDialog(null, "No se seleccion que tipo de usuario sera","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            // GUARDA LOS VALORES
        String nom = this.nomFRes.getText();
        int contrasena = Integer.parseInt(this.nomFRes4.getText());
        int ed = Integer.parseInt(this.nomFRes1.getText());
        int tel = Integer.parseInt(this.nomFRes2.getText());
        String mail = this.nomFRes3.getText();
        int tipo = this.listaTipo.getSelectedIndex() + 1;
        // EGNERA UN NUMERO ALEATORIO DE 9 DIGITOS PARA EL ID DEL USUARIO
        Random r = new Random();
        int id = r.nextInt((999999999 - 100000000) + 1) + 100000000;
        // CREA AL USUARIO
        Usuario user = new Usuario(nom,id,contrasena,ed,tel,mail,tipo);
        //System.out.println(nom +"\n" + ed +"\n" + tel +"\n" + mail +"\n" + tipo +"\n"  );
        
        try {
            this.registroAdmin.insert(user); // LOS REGISTRA EN  SU CARPETA CORRESPONDIENTE
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // ACTUALIZA LAS LISTAS PARA VER LOS CAMBIOS RECIENTES
        try {
            this.listaUsuarios.setModel(this.registroAdmin.actualizarJList());
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // PONE EN BLANCO LOS ESPACIO A LLENAR Y DESELECCIONA LA JLIST
        this.nomFRes.setText("");
        this.nomFRes1.setText("");
        this.nomFRes2.setText("");
        this.nomFRes3.setText("");
        this.nomFRes4.setText("");
        this.listaTipo.clearSelection();
        }
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void bajaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaFActionPerformed

    // BOTON DE ELEIMINAR USUARIO
    private void bajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaBtnActionPerformed
        // TODO add your handling code here:
        // VERIFICA QUE NO ESTE VACIO EL ESPACIO DEL CODIGO
        if(this.bajaF.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Favor de teclear el ID del cliente a eliminar","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        }
         else if(this.listaTipoB.getSelectedValue() == null)
            JOptionPane.showMessageDialog(null, "No se selecciono que tipo de usuario sera eliminado","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
         else // SI NO ESTA VACIO Y DESELECCIONADA LA LISTA
        {
             // GUARDA LOS DATOS
        int id = Integer.parseInt(this.bajaF.getText());
        int tipo = this.listaTipoB.getSelectedIndex() + 1;
        
        try {
            int r = this.registroAdmin.delete(id, tipo); // BORRA EL USUARIO
            if(r == 0) // SI NO FUE EXITOSO LO NOTIFICA CON UNA VENTANA DE NOTIFICACIONES
                 JOptionPane.showMessageDialog(null, "No se encontro al usuario con el ID\n" + id,"No se encontro ID",JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        // ACTUALIZA LISTAS
        try {
            this.listaUsuarios.setModel(this.registroAdmin.actualizarJList());
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            
        }// RESETEA LA SECCCION DE BAJA
            this.bajaF.setText("");
            this.listaTipoB.clearSelection();
        }
        
    }//GEN-LAST:event_bajaBtnActionPerformed
// BOTON MODIFICAR
    private void registrarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtn1ActionPerformed
        // TODO add your handling code here:
        // VERIFICA QUE TODO ESTE ELLENO
        if(this.nomFPro.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Favor escribir el nombre del producto ","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else if(this.listaTipoP.getSelectedValue() == null)
            JOptionPane.showMessageDialog(null, "No se selecciono que tipo de producto sera","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else if(this.comboAnio.getSelectedItem().toString().equals("Año") || this.comboExistencia.getSelectedItem().toString().equals("num"))
            JOptionPane.showMessageDialog(null, "No se selecciono que la exitencia o el año de creacion","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            // GUARDA DATOS
            String nom = this.nomFPro.getText();
            int tipo = this.listaTipoP.getSelectedIndex() + 1;
            int anio = Integer.parseInt(this.comboAnio.getSelectedItem().toString());
            int exis = Integer.parseInt(this.comboExistencia.getSelectedItem().toString());
            Random r = new Random();
            int cod = r.nextInt((999999 - 100000) + 1) + 100000; // NUMERO ALEATORIO DE 6 DIGITOS PARA EL ID DEL PRODUCTO
            
            
            try {
                this.registroAdminPro.insert(new Producto(cod,tipo,nom,anio,exis)); // REGISTRA EL PRODUCTO
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // RESETEA LA SECCION DE MODIFICAR Y ACTUALIZA LAS LISTAS
            try {
                this.listaProductos.setModel(this.registroAdminPro.actualizarJList());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                this.listaProductosAlquiler.setModel(this.registroAdminPro.actualizarJListAlquiler());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.comboAnio.setSelectedIndex(0);
            this.comboExistencia.setSelectedIndex(0);
            this.nomFPro.setText("");
            this.listaTipoP.clearSelection();
            
        }
    }//GEN-LAST:event_registrarBtn1ActionPerformed

    private void comboExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboExistenciaActionPerformed
// BOTON PARA ELIMINAR PRODUCTOS
    private void eleminarBtnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleminarBtnProActionPerformed
        // TODO add your handling code here:
        if(this.listaProductos.getSelectedValue() == null)
            JOptionPane.showMessageDialog(null, "No se selecciono ningun elemento de la lista","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else // SI ESTA SELECCIONADO EL PRODUCTO EN LA LISA
        {
            String s = this.listaProductos.getSelectedValue();
            String cods = s.substring(0, 6); // GUARDA EL CODIGO
            String tipo = s.substring(14,15); // gUARDA LA INICIAL DEL TIPO
            int cod = Integer.parseInt(cods);
            
            switch(tipo) // DEPENDIENDO DE LA INICIAL DEFINE EL TIPO
            {
                case "P":                
                    try {
                        this.registroAdminPro.delete(cod, 1); // bORRA SI ES PELICULA
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }                
                break;

                
                case "V":                    
                    try {
                        this.registroAdminPro.delete(cod, 2); // BORRA SI ES VIDEOJUEGO
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                break;
                
                case "C":                    
                    try {
                        this.registroAdminPro.delete(cod, 3); // BORRAS SI ES CARTELERA
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                break;
                
                
            }
            
            // RESETEO Y ACTUALIZACION
            try {
                this.listaProductos.setModel(this.registroAdminPro.actualizarJList());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                this.listaProductosAlquiler.setModel(this.registroAdminPro.actualizarJListAlquiler());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            this.listaProductos.clearSelection();
            
        }
        
        
    }//GEN-LAST:event_eleminarBtnProActionPerformed

    // mODIFICAR PRODUCTOS BOTON
    // LA MISA LOGICA DEL BOTON ELIMINAR PRODUCTOS PERO PIDE LOS DATOS PARA MODIFICAR DESPUES DE BORRAR LOS VIEJOS
    private void modificarBtnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnProActionPerformed
        // TODO add your handling code here:
         if(this.listaProductos.getSelectedValue() == null)
            JOptionPane.showMessageDialog(null, "No se selecciono ningun elemento de la lista","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            String s = this.listaProductos.getSelectedValue();
            String cods = s.substring(0, 6);
            int cod = Integer.parseInt(cods);
            
            String tipos = s.substring(14,15);
            
            
            switch(tipos)
            {
                case "P":                
                    try {
                        this.registroAdminPro.delete(cod, 1);
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }                
                break;

                
                case "V":                    
                    try {
                        this.registroAdminPro.delete(cod, 2);
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                break;
                
                case "C":                    
                    try {
                        this.registroAdminPro.delete(cod, 3);
                    } catch (Exception ex) {
                        Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                break;
                
                
            }
            
            // pIDIENDO DATOS NUEVOS
            String[] options = {"Pelicula", "Videojuego", "Cartelera"};
            int tipo = JOptionPane.showOptionDialog(null, "Es necesario que seleccione una opcion", "Tipo de Producto", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]) + 1;
            
            
            
            String nom = JOptionPane.showInputDialog(null, "Escriba nuevamente el nombre del producto", "Nombre del Producto", JOptionPane.INFORMATION_MESSAGE);
            
            String[] numeros = {
            "1","2","3","4","5","6","7","8","9","10",
            "11","12","13","14","15","16","17","18","19","20",
            "21","22","23","24","25","26","27","28","29","30",
            "31","32","33","34","35","36","37","38","39","40",
            "41","42","43","44","45","46","47","48","49","50",
            "51","52","53","54","55","56","57","58","59","60",
            "61","62","63","64","65","66","67","68","69","70",
            "71","72","73","74","75","76","77","78","79","80",
            "81","82","83","84","85","86","87","88","89","90",
            "91","92","93","94","95","96","97","98","99","100",
        };
        
            int exis = Integer.parseInt( (String) JOptionPane.showInputDialog(null, "Selecciona la existencia", "Existencia del Producto", JOptionPane.DEFAULT_OPTION, null, numeros, numeros[0]) );
            
            String[] numeros2 = new String[50];      
            Integer ano = 1970;
            for(int i = 0 ; i<50; i++)
            {
                numeros2[i] = ano.toString();
                ano++;
            }
            
            int anio = Integer.parseInt( (String) JOptionPane.showInputDialog(null, "Selecciona la existencia", "Existencia del Producto", JOptionPane.DEFAULT_OPTION, null, numeros2, numeros2[0]) );
             
             // RESTEO Y ACTUALIZACION
             try {
                 this.registroAdminPro.insert(new Producto(cod,tipo,nom,anio,exis));
             } catch (IOException ex) {
                 Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            try {
                this.listaProductos.setModel(this.registroAdminPro.actualizarJList());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                this.listaProductosAlquiler.setModel(this.registroAdminPro.actualizarJListAlquiler());
            } catch (IOException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            this.listaProductos.clearSelection();
            
        }
        
    }//GEN-LAST:event_modificarBtnProActionPerformed

    private void consultaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaFActionPerformed
// BOTON CONSULTA
    private void consultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBtnActionPerformed
        // TODO add your handling code here:
        if(this.consultaF.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Favor de ingresar el codigo de la producto a buscar","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        else if (this.listaTipoPConsulta.getSelectedValue() == null)
        {
            JOptionPane.showMessageDialog(null, "No se selecciono el tipo de producto a buscar","Faltan Datos",JOptionPane.INFORMATION_MESSAGE);
        }
        else // SI TODO ESTA LLENADO
        {
            // GUARDA DATOS
            int consul = Integer.parseInt(this.consultaF.getText());
            int tipo = this.listaTipoPConsulta.getSelectedIndex() + 1;
         
            try {
                Producto pro = this.registroAdminPro.bus(consul, tipo); // hACE UNA BUSQUEDA EN LAS CARPETAS STOCK
                 try {
                Producto proA = this.registroAdminPro.busAlquiler(consul, tipo); // HACE UNA BUSQUEDA EN LA CARPETA ALQUILER
                if(pro != null && proA != null) // SI SI ENCUENTRA AMBAS SE COMBINAN DATOS PARA MOSTRARLOS
                {
                    
                    String info = this.listaTipoPConsulta.getSelectedValue() + "\nCodigo: " + pro.getCodigo() + "\nNombre: " +  pro.getNombre() + "\nAño: " + pro.getCreacion() + "\nStock:  " + pro.getExistencia() +"\nAlquiler: " + proA.getExistencia() + "\nTotal: " + (pro.getExistencia()+proA.getExistencia());
                    JOptionPane.showMessageDialog(null, info,"Resultado de la busqueda",JOptionPane.PLAIN_MESSAGE);
                }
                else if(pro != null && proA == null) // EN CASO DE ENCONTRAR EN sTOCK MUESTRA SOLO DATOS DE aLQUILER
                {
                    String info = this.listaTipoPConsulta.getSelectedValue() + "\nCodigo: " + pro.getCodigo() + "\nNombre: " +  pro.getNombre() + "\nAño: " + pro.getCreacion() + "\nStock:  " + pro.getExistencia() +"\nAlquiler: 0 \nTotal: " + (pro.getExistencia());
                    JOptionPane.showMessageDialog(null, info,"Resultado de la busqueda",JOptionPane.PLAIN_MESSAGE);
                }
                else if(pro == null && proA != null) // LO MISMO CUANDO NO ENCUENTRA EN ALQUILER
                {
                    String info = this.listaTipoPConsulta.getSelectedValue() + "\nCodigo: " + proA.getCodigo() + "\nNombre: " +  proA.getNombre() + "\nAño: " + proA.getCreacion() + "\nStock: 0 \nAlquiler:" + proA.getExistencia() +  "\nTotal: " + (proA.getExistencia());
                    JOptionPane.showMessageDialog(null, info,"Resultado de la busqueda",JOptionPane.PLAIN_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Producto No Existente","Resultado de la busqueda",JOptionPane.ERROR_MESSAGE);
                }
                
                // RESETEO
                this.listaTipoPConsulta.clearSelection();
                this.consultaF.setText("");
            } catch (Exception ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (Exception ex) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
            
        }
        
    }//GEN-LAST:event_consultaBtnActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajaBtn;
    private javax.swing.JTextField bajaF;
    private javax.swing.JLabel borrarLabel;
    private javax.swing.JLabel borrarLabel1;
    private javax.swing.JLabel borrarLabel2;
    private javax.swing.JLabel borrarLabel3;
    private javax.swing.JPanel borrarPanel;
    private javax.swing.JPanel borrarPanel1;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JComboBox<String> comboExistencia;
    private javax.swing.JButton consultaBtn;
    private javax.swing.JTextField consultaF;
    private javax.swing.JButton eleminarBtnPro;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel fondoLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel listaLabel;
    private javax.swing.JLabel listaLabel1;
    private javax.swing.JLabel listaLabel10;
    private javax.swing.JLabel listaLabel11;
    private javax.swing.JLabel listaLabel12;
    private javax.swing.JLabel listaLabel13;
    private javax.swing.JLabel listaLabel14;
    private javax.swing.JLabel listaLabel15;
    private javax.swing.JLabel listaLabel16;
    private javax.swing.JLabel listaLabel2;
    private javax.swing.JLabel listaLabel3;
    private javax.swing.JLabel listaLabel4;
    private javax.swing.JLabel listaLabel5;
    private javax.swing.JLabel listaLabel6;
    private javax.swing.JLabel listaLabel7;
    private javax.swing.JLabel listaLabel8;
    private javax.swing.JLabel listaLabel9;
    private javax.swing.JPanel listaPanel;
    private javax.swing.JPanel listaPanelPro;
    private javax.swing.JPanel listaPanelProAlquiler;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JList<String> listaProductosAlquiler;
    private javax.swing.JList<String> listaTipo;
    private javax.swing.JList<String> listaTipoB;
    private javax.swing.JList<String> listaTipoP;
    private javax.swing.JList<String> listaTipoPConsulta;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JPanel mantenimientoPanel;
    private javax.swing.JButton modificarBtnPro;
    private javax.swing.JTextField nomFPro;
    private javax.swing.JTextField nomFRes;
    private javax.swing.JTextField nomFRes1;
    private javax.swing.JTextField nomFRes2;
    private javax.swing.JTextField nomFRes3;
    private javax.swing.JTextField nomFRes4;
    private javax.swing.JLabel nombreRes;
    private javax.swing.JLabel nombreRes1;
    private javax.swing.JLabel nombreRes10;
    private javax.swing.JLabel nombreRes11;
    private javax.swing.JLabel nombreRes2;
    private javax.swing.JLabel nombreRes3;
    private javax.swing.JLabel nombreRes4;
    private javax.swing.JLabel nombreRes5;
    private javax.swing.JLabel nombreRes6;
    private javax.swing.JLabel nombreRes7;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JButton registrarBtn1;
    private javax.swing.JLabel registroLabel;
    private javax.swing.JLabel registroLabel1;
    private javax.swing.JPanel registroPanel;
    private javax.swing.JPanel registroPanelP;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables

}
